"""empty message

Revision ID: da0323747a72
Revises: e503c00b48b3
Create Date: 2021-09-26 12:43:51.480959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0323747a72'
down_revision = 'e503c00b48b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('exam', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'exam')
    # ### end Alembic commands ###
